from typing import Union

from .create_grafana_snapshot_response import CreateGrafanaSnapshotResponse
from .model_view_response import ModelViewResponse
from .service_list_response import ServiceListResponse
from .service_response import ServiceResponse
from .service_view_response import ServiceViewResponse
from .ulca_asr_inference_response import ULCAAsrInferenceResponse
from .ulca_generic_inference_response import ULCAGenericInferenceResponse
from .ulca_ner_inference_response import ULCANerInferenceResponse
from .ulca_pipeline_inference_response import ULCAPipelineInferenceResponse
from .ulca_s2s_inference_response import ULCAS2SInferenceResponse
from .ulca_translation_inference_response import ULCATranslationInferenceResponse
from .ulca_transliteration_inference_response import (
    ULCATransliterationInferenceResponse,
)
from .ulca_tts_inference_response import ULCATtsInferenceResponse
from .ulca_vad_inference_response import ULCAVadInferenceResponse
from .ulca_llm_inference_response import ULCALLMInferenceResponse
from .ulca_ocr_inference_response import ULCAOCRInferenceResponse
from .ulca_text_lang_detection_inference_response import ULCATextLangDetectionInferenceResponse
from .ulca_speaker_diarization_inference_response import ULCASpeakerDiarizationInferenceResponse
from .ulca_language_diarization_inference_response import ULCALanguageDiarizationInferenceResponse
from .ulca_audio_lang_detection_inference_response import ULCAAudioLangDetectionInferenceResponse

ULCAInferenceResponse = Union[
    ULCAGenericInferenceResponse,
    ULCAAsrInferenceResponse,
    ULCATranslationInferenceResponse,
    ULCATransliterationInferenceResponse,
    ULCATtsInferenceResponse,
    ULCANerInferenceResponse,
    ULCAVadInferenceResponse,
    ULCALLMInferenceResponse,
    ULCAOCRInferenceResponse,
    ULCATextLangDetectionInferenceResponse,
    ULCASpeakerDiarizationInferenceResponse,
    ULCALanguageDiarizationInferenceResponse,
    ULCAAudioLangDetectionInferenceResponse,
]
