{
 "title": "Adopter DevOps View - Platform Health Copy",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\n<div style=\"text-align: center; font-size: 28px; font-weight: bold; color: #1f77b4;\">\nBhashini Health Dashboard\n</div>\n\n                        "
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 }, "options": { "content": "# System Health & Availability" } },
  {
   "title": "System Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\nsum(\r\n  increase(telemetry_obsv_requests_total{status=\"success\", endpoint!=\"/metrics\"}[24h])\r\n)\r\n/\r\nsum(\r\n  increase(telemetry_obsv_requests_total{endpoint!=\"/metrics\"}[24h])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate % Today vs SLA",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\nclamp_min(\r\n  sum(\r\n    increase(telemetry_obsv_requests_total{\r\n      status!=\"success\",\r\n      endpoint=~\"/nmt/translate|/tts/speak|/llm/generate|/pipeline\"\r\n    }[2h])\r\n  ), 0\r\n)\r\n/\r\nclamp_min(\r\n  sum(\r\n    increase(telemetry_obsv_requests_total{\r\n      endpoint=~\"/nmt/translate|/tts/speak|/llm/generate|/pipeline\"\r\n    }[2h])\r\n  ), 1\r\n)",
     "legendFormat": "Error Rate (24h)"
    },
    {
     "expr": "ai4x_error_rate_sla_target_percent",
     "legendFormat": "SLA"
    }
   ]
  },
  {
   "title": "Total API Calls ",
   "type": "stat",
   "description": "Total API calls made ",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(telemetry_obsv_requests_total{endpoint!=\"/metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall System Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000*(sum(rate(telemetry_obsv_request_duration_seconds_sum[5m]))\r\n/\r\nsum(rate(telemetry_obsv_request_duration_seconds_count[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Throughput (requests/min)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(telemetry_obsv_requests_total[1m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🚨 Overall Error  Rate Analysis ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "100 *\r\nclamp_min(\r\n  sum(\r\n    increase(telemetry_obsv_requests_total{\r\n      status!=\"success\",\r\n      endpoint=~\"/nmt/translate|/tts/speak|/llm/generate|/pipeline\"\r\n    }[2h])\r\n  ), 0\r\n)\r\n/\r\nclamp_min(\r\n  sum(\r\n    increase(telemetry_obsv_requests_total{\r\n      endpoint=~\"/nmt/translate|/tts/speak|/llm/generate|/pipeline\"\r\n    }[2h])\r\n  ), 1\r\n)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "📊 Request Volume Trends",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(telemetry_obsv_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 29 }, "options": { "content": "# Service Health" } },
  {
   "title": "Service Level Availability (%)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\nsum by (endpoint) (\r\n  increase(telemetry_obsv_requests_total{status=\"success\", endpoint!=\"/metrics\"}[1h])\r\n)\r\n/\r\nsum by (endpoint) (\r\n  increase(telemetry_obsv_requests_total{endpoint!=\"/metrics\"}[1h])\r\n)\r\n",
     "legendFormat": "{{service_endpoint}}"
    }
   ]
  },
  {
   "title": "Service Level Error Rate (%)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  1 -\r\n  sum by (endpoint) (\r\n    increase(telemetry_obsv_requests_total{status=\"success\", endpoint!=\"/metrics\"}[1h])\r\n  )\r\n  /\r\n  sum by (endpoint) (\r\n    increase(telemetry_obsv_requests_total{endpoint!=\"/metrics\"}[1h])\r\n  )\r\n)",
     "legendFormat": "{{service_endpoint}}"
    }
   ]
  },
  {
   "title": "Service Error Rate Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  1 -\r\n  sum by (endpoint) (\r\n    increase(telemetry_obsv_requests_total{status=\"success\", endpoint!=\"/metrics\"}[1h])\r\n  )\r\n  /\r\n  sum by (endpoint) (\r\n    increase(telemetry_obsv_requests_total{endpoint!=\"/metrics\"}[1h])\r\n  )\r\n)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Service Level Latency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000 *\r\n(\r\n  sum by (endpoint) (\r\n    rate(telemetry_obsv_request_duration_seconds_sum[24h])\r\n  )\r\n  /\r\n  sum by (endpoint) (\r\n    rate(telemetry_obsv_request_duration_seconds_count[24h])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Level SLA Compliance",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "avg by(endpoint) (telemetry_obsv_sla_compliance_percent)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "SLA Compliance",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(sla_type) (telemetry_obsv_sla_compliance_percent)",
     "legendFormat": "{{sla_type}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 55 }, "options": { "content": "# API Health" } },
  {
   "title": "Error Rate by Type",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\nsum by (status_series) (\r\n  increase(telemetry_obsv_errors_total{status_series!=\"2xx\"}[1h])\r\n)\r\n/\r\nscalar(\r\n  sum without(app, customer, domain, endpoint, error_type, status_series) (\r\n    increase(telemetry_obsv_errors_total{status_series!=\"2xx\"}[1h])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Level Availability (%)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\nsum by (endpoint) (\r\n  increase(telemetry_obsv_requests_total{status=\"success\", endpoint!=\"/metrics\"}[1h])\r\n)\r\n/\r\nsum by (endpoint) (\r\n  increase(telemetry_obsv_requests_total{endpoint!=\"/metrics\"}[1h])\r\n)\r\n",
     "legendFormat": "{{service_endpoint}}"
    }
   ]
  },
  {
   "title": "Service Level Latency (p90)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000 *\r\nhistogram_quantile(\r\n  0.90,\r\n  sum by (le, endpoint) (rate(telemetry_obsv_request_duration_seconds_bucket[5m]))\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Level Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000 *\r\nhistogram_quantile(\r\n  0.95,\r\n  sum by (le, endpoint) (rate(telemetry_obsv_request_duration_seconds_bucket[5m]))\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Level Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000 *\r\nhistogram_quantile(\r\n  0.99,\r\n  sum by (le, endpoint) (rate(telemetry_obsv_request_duration_seconds_bucket[5m]))\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Service Hop Latency ( ms )",
   "type": "stat",
   "description": "Average service hop latency for the pipeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000 * (sum by (component) (telemetry_obsv_component_latency_seconds_sum)\r\n/\r\nsum by (component) (telemetry_obsv_component_latency_seconds_count))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LLM Quota Usage per Customer",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\nsum by (customer) (\r\n  increase(telemetry_obsv_data_processed_total{data_type=\"llm_tokens\"}[30d])\r\n)\r\n/\r\nsum by (customer) (\r\n  telemetry_obsv_customer_llm_quota_per_month\r\n)\r\n",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "NMT Quota Usage per Customer",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\nsum by (customer) (\r\n  increase(telemetry_obsv_data_processed_total{data_type=\"nmt_characters\"}[30d])\r\n)\r\n/\r\nsum by (customer) (\r\n  telemetry_obsv_customer_nmt_quota_per_month\r\n)",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "TTS Quota Usage per Customer",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\nsum by (customer) (\r\n  increase(telemetry_obsv_data_processed_total{data_type=\"tts_characters\"}[30d])\r\n)\r\n/\r\nsum by (customer) (\r\n  telemetry_obsv_customer_tts_quota_per_month\r\n)",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 97 }, "options": { "content": "# Infra Health" } },
  {
   "title": "💾 CPU Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(endpoint) (telemetry_obsv_system_cpu_percent)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "🧠 Memory Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(endpoint) (telemetry_obsv_system_memory_percent)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Service Count",
   "type": "stat",
   "description": "Total number of services consumed",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 108 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (endpoint) (telemetry_obsv_requests_total))",
     "legendFormat": "{{service_type}}"
    }
   ]
  },
  {
   "title": "Peak Throughput (requests/min)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 108 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "telemetry_obsv_system_peak_throughput_rpm",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Error Rate ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\nclamp_min(\r\n  sum(\r\n    increase(telemetry_obsv_requests_total{\r\n      status!=\"success\",\r\n      endpoint=~\"/nmt/translate|/tts/speak|/llm/generate|/pipeline\"\r\n    }[2h])\r\n  ), 0\r\n)\r\n/\r\nclamp_min(\r\n  sum(\r\n    increase(telemetry_obsv_requests_total{\r\n      endpoint=~\"/nmt/translate|/tts/speak|/llm/generate|/pipeline\"\r\n    }[2h])\r\n  ), 1\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Service Latency ( ms )",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 114 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (endpoint) (\r\n  rate(telemetry_obsv_request_duration_seconds_sum{endpoint=~\"/tts/speak|/llm/generate|/nmt/translate|/pipeline\"}[1h])\r\n  /\r\n  rate(telemetry_obsv_request_duration_seconds_count{endpoint=~\"/tts/speak|/llm/generate|/nmt/translate|/pipeline\"}[1h])\r\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hourly LLM Tokens Processed ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 114 },
   "targets": [
    {
     "expr": "sum(increase(telemetry_obsv_llm_tokens_processed_total[1h]))",
     "legendFormat": "{{customer}}[hour]"
    },
    { "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Weekly SLA Compliance ",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 120 },
   "targets": [
    {
     "expr": "avg by (sla_type) (\r\n  avg_over_time(telemetry_obsv_sla_compliance_percent[1w])\r\n)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Hourly TTS Characters ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "targets": [
    {
     "expr": "sum(increase(telemetry_obsv_tts_characters_synthesized_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hourly API Calls by Service ",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (endpoint) (increase(telemetry_obsv_requests_total[1h]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Service Utilization Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
   "targets": [
    {
     "expr": "sum by (service) (telemetry_obsv_service_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hourly NMT Characters ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
   "targets": [
    {
     "expr": "sum(increase(telemetry_obsv_nmt_characters_translated_total[1h]))",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  }
 ]
}