{
 "title": "Adopter CEO View - Business Health",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Customer Reach" } },
  {
   "title": "Total Customers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (customer) (ai4x_requests_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Customers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (customer) (increase(ai4x_requests_total[7d]) > 0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Customer by Service",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (endpoint) (\r\n  count by (endpoint, customer) (ai4x_requests_total)\r\n)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Top 5 Customers by Traffic",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (customer) (increase(ai4x_requests_total[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Customers by Domain",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (domain) (\r\n  sum by (customer, domain) (ai4x_customer_metadata) > 0\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Reference App Users",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(app, ) (sum by(customer, app) (increase(ai4x_requests_total[30d]))) > 0",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 26 },
   "options": {
    "content": "# Customer Adoption & Engagement"
   }
  },
  {
   "title": "New Customers in last 60 days",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ai4x_customer_onboard_timestamp > time() - 60*24*60*60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Long Term Retained Customers ( > 2 years)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\r\n  (sum by (customer) (increase(ai4x_requests_total[30d])) > 0)\r\n  * on (customer) group_left()\r\n  (ai4x_customer_onboard_timestamp <= time() - 2*365*24*60*60)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 3 Customers by TTS Traffic",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "topk(3,\r\n100 *\r\nsum by (customer) (increase(ai4x_requests_total{endpoint=\"/tts/speak\"}[24h]))\r\n/\r\non() group_left()\r\nsum(increase(ai4x_requests_total{endpoint=\"/tts/speak\"}[24h]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 3 Customers by NMT Traffic",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "topk(3,\r\n100 *\r\nsum by (customer) (increase(ai4x_requests_total{endpoint=\"/nmt/translate\"}[24h]))\r\n/\r\non() group_left()\r\nsum(increase(ai4x_requests_total{endpoint=\"/nmt/translate\"}[24h]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 3 Customers by LLM Traffic",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "topk(3,\r\n100 *\r\nsum by (customer) (increase(ai4x_requests_total{endpoint=\"/llm/generate\"}[24h]))\r\n/\r\non() group_left()\r\nsum(increase(ai4x_requests_total{endpoint=\"/llm/generate\"}[24h]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}