{
 "title": "Adopter DevOps View - Metering",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "LLM Quota Usage per Customer",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\nsum by (customer) (\r\n  increase(ai4x_data_processed_total{data_type=\"llm_tokens\"}[30d])\r\n)\r\n/\r\nsum by (customer) (\r\n  ai4x_customer_llm_tokens_quota_per_month\r\n)\r\n",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "NMT Quota Usage per Customer",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\nsum by (customer) (\r\n  increase(ai4x_data_processed_total{data_type=\"nmt_characters\"}[30d])\r\n)\r\n/\r\nsum by (customer) (\r\n  ai4x_customer_nmt_chars_quota_per_month\r\n)",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "TTS Quota Usage per Customer",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\nsum by (customer) (\r\n  increase(ai4x_data_processed_total{data_type=\"tts_characters\"}[30d])\r\n)\r\n/\r\nsum by (customer) (\r\n  ai4x_customer_tts_chars_quota_per_month\r\n)",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "Hourly LLM Tokens Processed ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(ai4x_llm_tokens_processed_total[1h]))",
     "legendFormat": "{{customer}}[hour]"
    },
    { "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Hourly NMT Characters ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(ai4x_nmt_characters_translated_total[1h]))",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Hourly TTS Characters ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(increase(ai4x_tts_characters_synthesized_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}