{
 "title": "Adopter - Admin Dashboard - AgriSmart",
 "tags": [
  "tenant",
  "qos",
  "sla"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "System uptime",
   "type": "stat",
   "description": "Average uptime of different services ( NMT, TTS, LLM, ASR )",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ai4x_system_uptime_percent{time_window=\"1h\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Latency ( ms )",
   "type": "stat",
   "description": "Weighted Response Time Across all services",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\r\n  sum(rate(ai4x_request_duration_seconds_sum{customer=\"AgriSmart\"}[5m]))\r\n  /\r\n  sum(rate(ai4x_request_duration_seconds_count{customer=\"AgriSmart\"}[5m]))\r\n)\r\n # in milliseconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ai4x_errors_total{customer='AgriSmart'} or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (req/minute)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "60 * sum(rate(ai4x_requests_total{customer=\"AgriSmart\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLA Compliance ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ai4x_system_sla_compliance_percent{customer=\"AgriSmart\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QoS Performance Score by Service",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ai4x_qos_performance_score{customer=\"AgriSmart\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Service Availability Trends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "ai4x_qos_availability_percent{time_window=\"24h\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLA Violation Alerts",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (sla_type) (ai4x_system_sla_compliance_percent{sla_type=~\"availability|response_time|throughput\"})",
     "legendFormat": "{{sla_type}}"
    }
   ]
  },
  {
   "title": "Throughput Performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "requests_per_minute" } },
   "targets": [
    {
     "expr": "sum by(customer) (rate(ai4x_requests_total{customer=\"AgriSmart\"}[1m])) * 60",
     "legendFormat": "AgriSmart"
    }
   ]
  },
  {
   "title": "Response Time by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (endpoint) (ai4x_request_duration_seconds_sum{customer=\"AgriSmart\"})\r\n/\r\nsum by (endpoint) (ai4x_request_duration_seconds_count{customer=\"AgriSmart\"})",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Error Rate Trends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ai4x_errors_total{customer='AgriSmart'} or vector(0)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}