{
 "title": "Drilldown panels",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Service Level SLA Compliance",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(endpoint) (ai4x_system_sla_compliance_percent)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Calls by Service",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (endpoint) (ai4x_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Customers by Registration Year",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# Count customers by registration year using date labels\r\ncount by (year) (\r\n  label_replace(\r\n    ai4x_customer_metadata,\r\n    \"year\", \r\n    \"$1\", \r\n    \"onboarding_date\", \r\n    \"([0-9]{4})-.*\"\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}